# NAME- ROHIT
# STUDENT ID -0860615
# DAB311_lab1
# SECTION -045

# Library calls

In [18]:
import tensorflow as tf
print("tf.__version__", tf.__version__)

import torch
print("torch.__version__", torch.__version__)

import numpy as np
print("np.__version__", np.__version__)

tf.__version__ 2.17.0
torch.__version__ 2.4.0+cu121
np.__version__ 1.26.4


In [2]:
print(('GPU available for use?\n{0}').format(
    'GPU is available: True' if len(tf.config.list_physical_devices('GPU'))>0 else 'GPU is NOT available: False'
))

print(('\nYour available devices:\n{0}').format(
    [device.name for device in tf.config.experimental.list_physical_devices()]
))

GPU available for use?
GPU is NOT available: False

Your available devices:
['/physical_device:CPU:0']


# Basic TF operations

In [3]:
a = tf.constant(10)
b = tf.constant(20)

t1 = tf.multiply(a,b)
t2 = tf.add(a,b)
res = tf.divide(t1,t2)

# print the tensor object
print(res)

# print the value of the tensor object
tf.print(res, [res])

tf.Tensor(6.666666666666667, shape=(), dtype=float64)
6.666666666666667 [6.666666666666667]


#Comparing time spent using CPU vs GPU
As a simple operation, create a constant with tf.constant and an identity matrix with tf.eye, and measure the time spent for performing these operations

In [4]:
import time

cpu_slot = 0
gpu_slot = 0

# Using CPU at slot 0
with tf.device('/CPU:' + str(cpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    A = tf.constant([[3, 2], [5, 2]])
    print(tf.eye(2,2))

    # Printing how long it took with CPU
    end = time.time() - start
    print("CPU run time: %s \n" %np.round(end,6))

# Using the GPU at slot 0
with tf.device('/GPU:' + str(gpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    A = tf.constant([[3, 2], [5, 2]])
    print(tf.eye(2,2))

    # Printing how long it took with GPU
    end = time.time() - start
    print("GPU run time: %s \n" %np.round(end,6))

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
CPU run time: 0.012522 

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
GPU run time: 0.003339 



# Making tensors with tf.constant and tf.Variable

In [5]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])

# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])
print(A)

tf.Tensor(
[[3 2]
 [5 2]], shape=(2, 2), dtype=int32)


# Concatenation of two tensors with tf.concat

In [6]:
A = tf.constant([[3, 2],[5, 2]])
B = tf.constant([[9, 5],[1, 3]])

# Concatenate column-wise
AB_concatenated = tf.concat(values=[A, B], axis=1)
print(('Adding B\'s columns to A:\n{0}').format(AB_concatenated.numpy()))

# Concatenate row-wise
AB_concatenated = tf.concat(values=[A, B], axis=0)
print(('\nAdding B\'s rows to A:\n{0}').format(AB_concatenated.numpy()))

Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]

Adding B's rows to A:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


# Making tensors with tf.zeros and tf.ones

In [7]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(tensor.numpy()))

# Making a tensor filled with ones with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(tensor.numpy()))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Reshaping data with tf.reshape

In [8]:
# Making a tensor for reshaping
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor, shape = [1, 8])

print(('Tensor BEFORE reshape:\n{0}').format(tensor.numpy()))
print(('\nTensor AFTER reshape:\n{0}').format(reshaped_tensor.numpy()))

Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor AFTER reshape:
[[3 2 5 2 9 5 1 3]]


# Casting tensors to other data types with tf.cast

In [9]:
# Making a tensor
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]],
                      dtype=tf.float32)

# casting the tensor as int32
tensor_as_int = tf.cast(tensor, tf.int32)

print(('Tensor with floats:\n{0}').format(tensor.numpy()))
print(('\nTensor cast from float to int (just remove the decimal, no rounding):\n{0}').format(tensor_as_int.numpy()))

Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor cast from float to int (just remove the decimal, no rounding):
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


# Linear Algebra Operations
# Below operations are commonly used in implementing/modifying algorithms

Transposing tensor with tf.transpose
Matrix Multiplication with tf.matmul
Element-wise multiplication with tf.multiply
Identity Matrix with tf.eye
Determinant with tf.linalg.det
Dot Product with tf.*tensordot*

# Transposing a tensor with tf.transpose

In [10]:
# create Matrix A
A = tf.constant([[3, 7],[1, 9]])
print(('The original matrix A:\n{0}').format(A))
A = tf.transpose(A)
print(('The transposed matrix A:\n{0}').format(A))

The original matrix A:
[[3 7]
 [1 9]]
The transposed matrix A:
[[3 1]
 [7 9]]


# Matrix multiplication with tf.matmul

In [11]:
# Some Matrix A
A = tf.constant([[3, 7], [1, 9]])
# Some vector v
v = tf.constant([[5],[2]])
# Matrix multiplication of A.v^T
Av = tf.matmul(A, v)
print(('Matrix Multiplication of A and v results in a new Tensor:\n{0}').format(Av))

Matrix Multiplication of A and v results in a new Tensor:
[[29]
 [23]]


# Element-wise multiplication with tf.multiply

In [12]:
A = tf.constant([[3, 7], [1, 9]])
v = tf.constant([[5],[2]])

# Element-wise multiplication
Av = tf.multiply(A, v)
print(('Element-wise multiplication of A and v results in a new Tensor:\n{0}').format(Av))

Element-wise multiplication of A and v results in a new Tensor:
[[15 35]
 [ 2 18]]


# Making an identity matrix with tf.eye

In [13]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9],
                 [2, 5]])

# Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(rows, columns))

# Making identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)

print(('\nThe identity matrix of A:\n{0}').format(A_identity.numpy()))

Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]


# Finding the determinant with tf.linalg.det

In [14]:
# Reusing Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Determinant must be: half, float32, float64, complex64, complex128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A: determinant formulat: a*d-b*c = 3*9-1*7 = 20
det_A = tf.linalg.det(A)

print(('The determinant of A:\n{0}').format(det_A))

The determinant of A:
20.0


# find the dot product with tf.tensordot

In [15]:
# Defining a 3x3 matrix
A = tf.constant([[3, 8, 5],
                 [1, 2, 1],
                 [5, 3, 2]])

# Defining another 3x3 matrix
B = tf.constant([[2, 5, 0],
                 [1, 0, 5],
                 [3, 1, 5]])

# Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(('Dot product of A.B^T results in a new Tensor:\n{0}').format(dot_AB))

# Which is the same as matrix multiplication in this instance (axes=1)
# Matrix multiplication of A and B
AB = tf.matmul(A, B)

print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format(AB))

Dot product of A.B^T results in a new Tensor:
[[29 20 65]
 [ 7  6 15]
 [19 27 25]]

Matrix Multiplication of A.B^T results in a new Tensor:
[[29 20 65]
 [ 7  6 15]
 [19 27 25]]


# Basic pytorch operations

In [16]:
# initializing a numpy array
a = np.array(1)

# initializing a tensor
b = torch.tensor(1)
print("a:", a)
print("b:", b)

a: 1
b: tensor(1)


In [17]:
# 2 matrices of size 2x3 into a 3d tensor 2x2x3
d = [ [[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]] ]
print("shape of the list:", np.array(d).shape)

d = torch.Tensor(d) # array from python list
print("shape of the tensor:", d.size())

# the first index is the depth
z = d[0] + d[1]
print("adding up the two matrices of the 3d tensor:",z)

shape of the list: (2, 2, 3)
shape of the tensor: torch.Size([2, 2, 3])
adding up the two matrices of the 3d tensor: tensor([[ 8., 10., 12.],
        [15., 17., 19.]])
